export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED ";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const FORGOT_EMAIL_SUCCESS = "FORGOT_EMAIL_SUCCESS";
export const FORGOT_EMAIL_FAILED = "FORGOT_EMAIL_FAILED";

export const LOGOUT = "LOGOUT";

export const IS_LOADING = "IS_LOADING";
export const IS_NOT_LOADING = "IS_NOT_LOADING";

export const SHOW_EDIT_WINDOW = "SHOW_EDIT_WINDOW";
export const SHOW_NEW_WINDOW = "SHOW_NEW_WINDOW";
